### ISSUE TITLE
Make an alias of !balance: !bal

### ISSUE THREAD

**Issue by MM-coder** [FoggyIO/Wilfred#22]
Its simple enough.

**Comment by FoggyIO** [comment]
There isn't even a !balance command? Everything is displayed through !profile

**Comment by iSaluki** [comment]
That could be done. But why would we do that? You can see everything on !profile so !bal and !balance seem a bit pointless.

**Comment by FoggyIO** [comment]
In my opinion it's kind of just adding redundant code, I can alias !profile into a !bal command but I personally don't feel it is needed, everyone was fine with the !profile command until someone accidentally did !balance and now everyone seems to dislike !profile.

**Comment by iSaluki** [comment]
I couldn't agree with that more.

**Comment by BluePhoenixGame** [comment]
Same

**Comment by volcanicer** [comment]
We honestly don't need another command for simply checking your balance. In my opinion it would just be useless to have since there is a better version (!profile) of checking user balance.

**Comment by FoggyIO** [comment]
Since the general feedback on this suggestion is on the side of not implementing the command due to the fact !profile already does that, I'll be closing this suggestion. Feel free to re-open it if you have any further suggestions to extend the original idea.

**Issue Closed - Suggestion Declined**
