### ISSUE TITLE
$0 Payments

### ISSUE THREAD

**Issue by LukeScarion** [FoggyIO/Wilfred#25]
**Describe the bug**
Users can pay $0

**To Reproduce**
1. Pay a user $0
2. !pay @SyntaxPrime 0
3. Observe the transaction complete even though there is no transaction here.

**Expected behavior**
The bot should not let you since you're not actually paying anything.

**Comment by FoggyIO** [comment]
This has already been reported in Pull Request #24 - Fix has been applied to In-Dev Branch on commit 8b83c65

**Issue Closed - Duplicate**
