### ISSUE TITLE
Make a coinbooster that is purchasable

### ISSUE THREAD

**Issue by Cobble8** [FoggyIO/Wilfred#40]
**This would be available to everyone to purchase.**
Make it like maybe 2x coin boost that lasts for a certain amount of time (maybe a week or something) That would cost something like 1k coins maybe?
- Cobble8#0881

**Comment by volcanicer** [comment]
I don't think that this is a good idea. It creates an unfair advantage and would cause some issues.

**Comment by GeorgeCY2** [comment]
**yep**

**Comment by FoggyIO** [comment]
I'm on the fence about this, I don't see any sense in spending coins to get more coins? We do have plans for purchasable cosmetics within the soft-currency and may add Global Boosters (i.e. someone can activate a booster that applies to everyone). In addition to this, we're working on a create like system that may give you personal boosters.

**Comment by FoggyIO** [comment]
**Idea Pending**

I am going to bring this up with Administration in the next meeting in regards to the future cosmetic update. Sit tight!
