### ISSUE TITLE
Making profile a image

### ISSUE THREAD

**Issue by EpicShardGamingYT** [FoggyIO/Wilfred#42]
**Describe the solution you'd like**
A image instead of a embed, you have a lot of freedom with it

**Describe alternatives you've considered**

**Comment by volcanicer** [comment]
I don't agree with this idea. Seems like too much unnecessary work just to display a profile which looks just fine in the embed.

**Comment by EpicShardGamingYT** [comment]
@volcanicer If the work is the problem i can make a pr, it isnt that hard tbh

**Comment by volcanicer** [comment]
I just don't think it would be a great idea in general. The embed is just fine.

**Comment by FoggyIO** [comment]
This is too much work and unpractical in my opinion, my experience with image generators have always caused me problems, namely caching and bandwidth issues. This would also take up too many resources, remember this is only hosted on a Raspberry Pi and I have no intention of allocating my VMSphere/VMWare cluster resources to this. Additionally it makes it impractical to make quick changes, we're talking about having to change vectors etc.

Normally I don't close ideas without letting discussion take place on them but this is too impractical to implement from a developers standpoint, I don't have much time either, I'm a student and I'd rather have the easy option of using embeds that look fine in my opinion than having to worry about having to make a lot of changes for something like the Pumpkin Placeholder.

With that said.
**Issue Closed - Idea Rejected (Impractical)**
