### ISSUE TITLE
Add a link to #faqs in the Welcome embed

### ISSUE THREAD

**Issue by volcanicer** [FoggyIO/Wilfred#54]
New people to the server need a bit of a pointer, so a mention of channel #faqs when people join would be helpful to get new people familiar with the server and Wilfred's commands.

**Comment by FoggyIO** [comment]
This will be done, however this isn't essentially a bit suggestion, the embeds are just sent through the bot to make things look nicer. I am going to make the FAQs channel visible for users in #gate but potentially a duplicate copy of it so bots cannot scrape users.

**Issue Closed - Reasons Above**
