### ISSUE TITLE
Add a !tag command

### ISSUE THREAD

**Issue by mrthordavis** [FoggyIO/Wilfred#62]
As the title says I think a `!tag` command would come in quite useful with the large amount of new people joining and wanting help for their discord bots. This would make it easier for people to explain stuff ex. indentation.

**Comment by volcanicer** [comment]
I like this idea. It's very useful to help people get started, and seeing other servers with the same command, it's a huge benefit and time saver.

- Suggestion label added

**Comment by FoggyIO** [comment]
**Status Updated**

This is now in progress and will most likely be released in the next update cycle.

Currently planned "tags":
**Asking Questions**
**Dev Help Pings**
**Code Blocks**
**Token Information**
**Installing discord.py**
**Python Downloads**

**Comment by mrthordavis** [comment]
Awesome, but having the ability to add tags via a command would be nice (staff/proficients only). This would allow us to quickly add new and useful tags without having to write some code.

**Tags _I_ think would be useful:**
- Checking code for unclosed brackets, missing colons, correct capitalization, etc. . .
- MacOS error + fix
- Python 3.7 error + fix
- Multiple `on_message()` 'commands'

**Comment by GeorgeCY2** [comment]
i don't think leaving the tag command only for proficients, since for other members (who know how to help the members for issues, not for those who don't) to use the tag for common questions

**Comment by GeorgeCY2** [comment]
(nvm sorry now readed it)
