### ISSUE TITLE
Bug Report: Ability to rank up multiple times to the same rank causing negative balance

### ISSUE THREAD

**Issue by FoggyIO** [FoggyIO/Wilfred#63]
**Describe the bug**
During a Lag Spike, using !rankup twice can allow you to rank yourself up to the same rank twice, double charging you and also sending you into negative balance if relevant.

**To Reproduce**
Steps to reproduce the behaviour:
1. Send !rank up twice without letting the bot have a chance to open the Rankup Dialog
1. Press 👍 on any of the dialogues.

**Expected behaviour**
Something should prevent a double rank-up to the same rank and double the cost. The system should have some sort of context to whether a rank-up dialogue is already active for that user or not.

**Screenshots**
https://cdn.discordapp.com/attachments/473284065315913739/508026479582642230/unknown.png
https://cdn.discordapp.com/attachments/473284065315913739/508026596788273155/unknown.png

**Additional context**
High Priority but the fix can wait until next update cycle, not full on urgent since we can reimburse but it is an inconvenience to fix needs to be applied prior to Sunday's update cycle.

**Comment by volcanicer** [comment]
Bug Report no longer valid as of 24/11/2018, as it introduces the Leveling system, and deprecates !rankup and !prestige.

**Comment by FoggyIO** [comment]
**Issue Closed - No Longer Valid**
