### ISSUE TITLE
Add a !jumbo command

### ISSUE THREAD

**Issue by mrthordavis** [FoggyIO/Wilfred#66]
I would love to see the addition of a `!jumbo <emoji>` command. The command is pretty simple and should just send the given emoji, but bigger. 
I also thought of maybe implementing it as a perk to one of the Regular+ roles to avoid it flooding channels ¯\_(ツ)_/¯

**Comment by GeorgeCY2** [comment]
well, I don't think it's necessary, since what do i do is type `shrug` into my dictionary with the shrug emoji and when i type `shrug` i can convert it to ¯\_(ツ)_/¯ easily with my keyboard on phone. And if i am on pc, the simple command is `/shrug` on discord, so i don't see any point on adding it
